builds:
  - main: ./cmd/sneasler
    ldflags:
      - -s -w -X github.com/frantjc/sneasler.Semver={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
changelog:
  use: github
  filters:
    exclude:
      - merge conflict
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
dockers:
  - image_templates:
      - ghcr.io/frantjc/sneasler:{{ .Version }}
      - ghcr.io/frantjc/sneasler:{{ .Major }}.{{ .Minor }}
      - ghcr.io/frantjc/sneasler:{{ .Major }}
      - ghcr.io/frantjc/sneasler:latest
    dockerfile: goreleaser.dockerfile
    extra_files:
      - app/
      - .dockerignore
      - package.json
      - remix.config.js
      - remix.env.d.ts
      - server.js
      - yarn.lock
