---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sneasler
  namespace: sneasler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sneasler
subjects:
  - kind: ServiceAccount
    name: sneasler
    namespace: sneasler
roleRef:
  kind: ClusterRole
  name: sneasler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: sneasler
  namespace: sneasler
spec:
  serviceAccountName: sneasler
  containers:
    - name: sneasler
      image: ghcr.io/frantjc/sneasler:0.1.2
      args:
        - controller
      ports:
        - containerPort: 6000
        - containerPort: 6001
        - containerPort: 6002
