---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: sneasler
rules:
  - apiGroups:
      - frantj.cc
    resources:
      - sneaslers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - frantj.cc
    resources:
      - sneaslers/finalizers
    verbs:
      - update
  - apiGroups:
      - frantj.cc
    resources:
      - sneaslers/status
    verbs:
      - get
      - patch
      - update
